Removed unnecessary include for curl_md4 because it duplicates a lot of what is already included in curl_hmac.h.
curl_setup_once.h:103:8: error: redefinition of 'timeval'
struct timeval